version: "3.9"
services:
  captcha-jwt-auth:
    image: "captcha-jwt-auth:master"
    container_name: captcha-jwt-auth
    volumes:
      - ./log:/app/log
      - ./data:/app/data
    env_file:
     - ./.env
    ports:
      - "3000:3000"
    restart: unless-stopped
